# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator.LAPTOP-S0NU6TDL/OneDrive - Singapore University of Technology and Design/10. Term 6/Digital Systems Lab/seedGen/seedGen.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator.LAPTOP-S0NU6TDL/OneDrive - Singapore University of Technology and Design/10. Term 6/Digital Systems Lab/seedGen/seedGen.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator.LAPTOP-S0NU6TDL/OneDrive - Singapore University of Technology and Design/10. Term 6/Digital Systems Lab/seedGen/seedGen.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Administrator.LAPTOP-S0NU6TDL/OneDrive - Singapore University of Technology and Design/10. Term 6/Digital Systems Lab/seedGen/seedGen.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator.LAPTOP-S0NU6TDL/OneDrive - Singapore University of Technology and Design/10. Term 6/Digital Systems Lab/seedGen/seedGen.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator.LAPTOP-S0NU6TDL/OneDrive - Singapore University of Technology and Design/10. Term 6/Digital Systems Lab/seedGen/seedGen.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
